### ISSUE TITLE
Why does this problem keep occurring?

### ISSUE THREAD

**Issue by aiwujiwudeguyue** [bnb-chain/bsc-snapshots#203]
![Screenshot_2023-01-09-10-38-29-081_com microsoft rdc androidx](https://user-images.githubusercontent.com/104301173/211234675-1334525b-8234-4ad6-b1b3-5a47b4643578.jpg)

**Comment by aiwujiwudeguyue** [comment]
On average, there is no interruption in half an hour

isaacyuno ***@***.***> 于 2023年1月9日周一 上午11:09写道：

**Comment by aiwujiwudeguyue** [comment]
On average, interruptions occur within half an hour

大哥 ***@***.***> 于 2023年1月9日周一 上午11:10写道：

**Comment by isaacyuno** [comment]
Looks like your network issue, I tried from my side before, and it doesn't happen that often

**Comment by kris-ss** [comment]
Hello, this should be fixed now. Please try again now with the latest snapshot - https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20230110.tar.lz4

**Comment by liczn** [comment]
I have the same problem, event with the latest snapshot (20230122). I get an 500 http code so it seems to come from the server.

**Comment by kris-ss** [comment]
@liczn Hello, I tried this on my end and so far it's downloading the snapshot without any issues. Please try it with aria2c.

aria2c -o geth.tar.lz4 -s14 -x14 -k100M https://download.bsc-snapshot.workers.dev/geth-20230122.tar.lz4 -o geth.tar.lz4

![Screen Shot 2023-01-23 at 12 38 07 PM](https://user-images.githubusercontent.com/113088090/213996609-55b3ec8a-172b-4be1-b7b9-4a8b42603a35.png)

**Comment by liczn** [comment]
Good it fixes it. The download still crashes every few hours but at least I can resume it with aria.

**Comment by aiwujiwudeguyue** [comment]
Can you recommend the server provider you used?

**Comment by aiwujiwudeguyue** [comment]
Can you recommend the server provider you used?

**Comment by liczn** [comment]
@aiwujiwudeguyue 

I used the exact command provided by @kris-ss
